/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package areaperimetro;

//Importamos las clases necesarias (esto si las clases se encuentran en otro paquete)
import clases.Hexagono;
import clases.Rectangulo;
import clases.TrianguloRectangulo;

/**
 *
 * @author Dario
 */
public class AreaPerimetro extends javax.swing.JFrame {

   //Declaramos los objetos de cada clase  
   Hexagono hexagono;
   Rectangulo rectangulo;
   TrianguloRectangulo triangulo;
    
   //Bandera que nos idicara en que posicion del radiobutton nos encotramos
   //1: cuadrado, 2: triangulo, 3: hexagono
   int band=1;
    
    public AreaPerimetro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        radiogroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        resulArea = new javax.swing.JLabel();
        resulPerimetro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ejercicio X");

        radiogroup.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Rectangulo");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        radiogroup.add(jRadioButton3);
        jRadioButton3.setText("Triangulo Rectangulo");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        radiogroup.add(jRadioButton4);
        jRadioButton4.setText("Hexagono");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        num1.setToolTipText("hola");
        num1.setName("hola");

        label1.setText("Lado A");

        label2.setText("Lado B");

        resulArea.setText("Area:");

        resulPerimetro.setText("Perimetro:");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1)
                            .addComponent(label2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(num2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resulArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resulPerimetro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1)
                    .addComponent(resulArea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2)
                    .addComponent(resulPerimetro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        //Metodo que se dispara al seleccionar el RadioButton Rectangulo
        //Cambiamos el texto al poligono correspondiente
        label1.setText("Lado A");
        label2.setText("Lado B");
        
        //Hacemos visible el TextField para el segundo numero
        num2.setVisible(true);
        
        //Modificamos la bandera al poligono correspondiente
        band=1;
        
        //Limpiamos los campos de entrada y los resultados
        //Metodo definido mas a bajo
        deleteAreaPerimetro();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
       //Metodo que se dispara al seleccionar el RadioButton Triangulo rectangulo
        
       //Cambiamos el texto al poligono correspondiente
       label1.setText("Lado A");
       label2.setText("Lado B");
       
       //Hacemos visible el TextField para el segundo numero
       num2.setVisible(true);
       //Modificamos la bandera al poligono correspondiente
       band=2;
       //Limpiamos los campos de entrada y los resultados
       //Metodo definido mas a bajo
       deleteAreaPerimetro();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
       //Metodo que se dispara al seleccionar el RadioButton Hexagono
       //Cambiamos el texto al poligono correspondiente
       label1.setText("Lado");
       label2.setText("");
       
       //Hacemos invisible el TextField para el segundo numero
       num2.setVisible(false);
       //Modificamos la bandera al poligono correspondiente
       band=3;
       //Limpiamos los campos de entrada y los resultados
       //Metodo definido mas a bajo
       deleteAreaPerimetro();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    //Metodo para limpiar los TextField y Label de resultado en cada cambio de los radio button
    public void deleteAreaPerimetro(){
        //Limpiamos los label de resultados
        resulArea.setText("Area: ");
        resulPerimetro.setText("Perimetro: ");
        //Limpiamos los TextField de ingreso de datos
        num1.setText("");
        num2.setText("");
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    //Metodo que se dispara al presionar el boton de Calcular  
    //Obtenemos el texto que se encuentra en cada TextField     
    String l1 = num1.getText();
    String l2 = num2.getText();    
    
    //Evaluamos la bandera para saber que radiobutton esta seleccionado
    if(band==1){
       //Llamamos el metodo correspondiente para el calculo del Area y Perimetro del Rectangulo
       //El metodo definido mas abajo, recibe como argumentos de entrada l1 y l2 convertido a enteros
       procesoRectangulo(Integer.parseInt("0"+l1), Integer.parseInt("0"+l2));
    }else if(band==2){
       //Llamamos el metodo correspondiente para el calculo del Area y Perimetro del Triangulo Rectangulo
       //El metodo definido mas abajo, recibe como argumentos de entrada l1 y l2 convertido a enteros 
       procesoTriangulo(Integer.parseInt("0"+l1), Integer.parseInt("0"+l2));
    }else{
      //Llamamos el metodo correspondiente para el calculo del Area y Perimetro del Hexagono
       //El metodo definido mas abajo, recibe como argumentos de entrada l1  convertido a entero  
       procesoHexagono(Integer.parseInt("0"+l1));  
    }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //Metodo para el calculo del Area y Perimetro del Rectangulo
//    Visibilidad: public, Retorno: void (no retorno), Nombre: procesoRectangulo, Argumentos: int ladoA, int ladoB
    public void procesoRectangulo(int ladoA, int ladoB){
//        Evaluamos si el objeto rectangulo de la clase Rectangulo es nulo
//        Si es nulo, se debe a que no esta instanciado o a que no se a asignado nada a al objeto        
        if(rectangulo==null)
            //Si es Nulo, invocamos el constructor para crear un nuevo objeto
            rectangulo= new Rectangulo(ladoA, ladoB);
        else{
            //En caso contrario, modificamos el LadoA y LadoB 
            rectangulo.setLadoA(ladoA);
            rectangulo.setLadoB(ladoB);    
        }
        //Llamamos el metodo que permite imprimir el area y el perimetro
        //Metodo definido mas abajo
        setAreaPerimetro(rectangulo.getArea(), rectangulo.getPerimetro());
    }
    //Metodo para el calculo del Area y Perimetro del Triangulo Rectangulo
//    Visibilidad: public, Retorno: void (no retorno), Nombre: procesoTriangulo, Argumentos: int ladoA, int ladoB    
    public void procesoTriangulo(int ladoA, int ladoB){
//        Evaluamos si el objeto triangulo de la clase Triangulo es nulo
//        Si es nulo, se debe a que no esta instanciado o a que no se a asignado nada a al objeto  
        if(triangulo==null)
            //Si es Nulo, invocamos el constructor para crear un nuevo objeto
            triangulo= new TrianguloRectangulo(ladoA, ladoB);
        else{
            //En caso contrario, modificamos el LadoA y LadoB 
            triangulo.setLadoA(ladoA);
            triangulo.setLadoB(ladoB);
        }    
        //Llamamos el metodo que permite imprimir el area y el perimetro
        //Metodo definido mas abajo
        setAreaPerimetro(triangulo.getArea(), triangulo.getPerimetro());
    }
    
    //Metodo para el calculo del Area y Perimetro del Hexagono
//    Visibilidad: public, Retorno: void (no retorno), Nombre: procesoHexagono, Argumentos: int lado
    public void procesoHexagono(int lado){
//        Evaluamos si el objeto hexagono de la clase Hexagono es nulo
//        Si es nulo, se debe a que no esta instanciado o a que no se a asignado nada a al objeto  
        if(hexagono==null)
            //Si es Nulo, invocamos el constructor para crear un nuevo objeto
            hexagono= new Hexagono(lado);
        else
            //En caso contrario, modificamos el Lado 
            hexagono.setLado(lado);
        //Llamamos el metodo que permite imprimir el area y el perimetro
        //Metodo definido mas abajo        
        setAreaPerimetro(hexagono.getArea(), hexagono.getPerimetro());
    }
    
    //Metodo para imprimir el Area y el perimetro
    //Visibilidad: public, Retorno: void (No Retorno), Nombre: setAreaPerimetro, Argumentos: float area y float perimetro
    public void setAreaPerimetro(float area, float perimetro){
        //Imprimimos el Area
        resulArea.setText("Area: "+area);
        //Imprimimos el Perimetro
        resulPerimetro.setText("Perimetro: "+perimetro);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaPerimetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaPerimetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaPerimetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaPerimetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AreaPerimetro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.ButtonGroup radiogroup;
    private javax.swing.JLabel resulArea;
    private javax.swing.JLabel resulPerimetro;
    // End of variables declaration//GEN-END:variables
}
